name: markdown_from_url
description: Just a simple library to fetch raw markdown from the web and render it to a widget
version: 0.0.1
homepage: https://github.com/felixwortmann/markdown_from_url

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_markdown: ^0.3.4
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
